//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFWP.Language {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FFWP.Language.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Add Profile benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string addbtt {
            get {
                return ResourceManager.GetString("addbtt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Mod benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string addmod {
            get {
                return ResourceManager.GetString("addmod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Drag and drop the mods you want to use. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string addmodinf {
            get {
                return ResourceManager.GetString("addmodinf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Profile benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string addprofile {
            get {
                return ResourceManager.GetString("addprofile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Profile benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string addtool {
            get {
                return ResourceManager.GetString("addtool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specified Profile Already Exists! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string alex {
            get {
                return ResourceManager.GetString("alex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FFGapple is Already Running in the Background! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string alwork {
            get {
                return ResourceManager.GetString("alwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change parental control settings benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string apc {
            get {
                return ResourceManager.GetString("apc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Try Auto Login Module: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string autologin {
            get {
                return ResourceManager.GetString("autologin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Come back benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string back {
            get {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FFGapple Currently In A Maintenance. Try Again After a Time! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string bakim {
            get {
                return ResourceManager.GetString("bakim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your E-Mail and Password are deprived of the new encryption method, re-create the profile as soon as possible. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string base64 {
            get {
                return ResourceManager.GetString("base64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Join the FFGapple Beta Program benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string beta {
            get {
                return ResourceManager.GetString("beta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Choose your &quot;Minecraft Vanilla&quot; version. These versions are the stock versions of Minecraft, and you cannot add mods later. You can use Fabric or Forge to use mods. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string bugligapple2332ezwinbusurumevanilyacort {
            get {
                return ResourceManager.GetString("bugligapple2332ezwinbusurumevanilyacort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Build:  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string build {
            get {
                return ResourceManager.GetString("build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FFGapple Can&apos;t Catch The Error, Please Write A Issue On GitHub! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string catchno {
            get {
                return ResourceManager.GetString("catchno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Online (Mojang / Microsoft Account) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string cevrim {
            get {
                return ResourceManager.GetString("cevrim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Offline benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string cevrimdi {
            get {
                return ResourceManager.GetString("cevrimdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create Resource Pack. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string customcre {
            get {
                return ResourceManager.GetString("customcre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There must be a special directory in your profile for this! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string customerr {
            get {
                return ResourceManager.GetString("customerr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Custom Skin Generator (Single Player) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string customski {
            get {
                return ResourceManager.GetString("customski", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You must have more than 1 profile to delete a profile! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string delerr {
            get {
                return ResourceManager.GetString("delerr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no directory specifically specified in your profile! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string direr {
            get {
                return ResourceManager.GetString("direr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Donate to FFGapple benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string donate {
            get {
                return ResourceManager.GetString("donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   4GB RAM For Game (FFGapple Optimizing Tool) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string dortgb {
            get {
                return ResourceManager.GetString("dortgb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Download! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string download {
            get {
                return ResourceManager.GetString("download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disable parental controls benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string dpc {
            get {
                return ResourceManager.GetString("dpc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Required RAM capacity not met! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string dusuk {
            get {
                return ResourceManager.GetString("dusuk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit Profile benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string edittool {
            get {
                return ResourceManager.GetString("edittool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Screen: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ekrantext {
            get {
                return ResourceManager.GetString("ekrantext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string enter {
            get {
                return ResourceManager.GetString("enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable parental controls benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string epc {
            get {
                return ResourceManager.GetString("epc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yes benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string evt {
            get {
                return ResourceManager.GetString("evt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FFGapple Launcher is an open source Minecraft launcher. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string fabdik1 {
            get {
                return ResourceManager.GetString("fabdik1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It is not affiliated with Microsoft or Mojang. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string fabdik2 {
            get {
                return ResourceManager.GetString("fabdik2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FFGapple Launcher and its makers are not responsible for the possible problems caused by the libraries and installation packages it contains. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string fabdik3 {
            get {
                return ResourceManager.GetString("fabdik3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Press Yes to indicate that you have read and understood this text and that you want to continue with the program, press No to reject it. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string fabdik4 {
            get {
                return ResourceManager.GetString("fabdik4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You cannot install &quot;Fabric&quot; without a special directory! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string fabricdir {
            get {
                return ResourceManager.GetString("fabricdir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start faster benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string faster {
            get {
                return ResourceManager.GetString("faster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You are using an old version of FFGapple. The new version is being downloaded and will be installed. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ffupdating {
            get {
                return ResourceManager.GetString("ffupdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fill in the red marked places! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string fillerr {
            get {
                return ResourceManager.GetString("fillerr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Notification: Since the owners of Forge Minecraft do not want the Forge installation to be automated, automatic Forge installation is disabled, we have prepared the Forge installation environment for you, to download: https://files.minecraftforge.net/net/minecraftforge/forge/ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string forgeerr {
            get {
                return ResourceManager.GetString("forgeerr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do You Want To Do Fresh Install? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string fresh {
            get {
                return ResourceManager.GetString("fresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FFGapple - Have Fun :) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string fun {
            get {
                return ResourceManager.GetString("fun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Width: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string genistext {
            get {
                return ResourceManager.GetString("genistext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Login benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string giriscrack {
            get {
                return ResourceManager.GetString("giriscrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Login benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string girismojang {
            get {
                return ResourceManager.GetString("girismojang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Take Me Back! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string grdn {
            get {
                return ResourceManager.GetString("grdn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string hyr {
            get {
                return ResourceManager.GetString("hyr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2GB RAM For Game (FFGapple Optimizing Tool) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ikigb {
            get {
                return ResourceManager.GetString("ikigb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check Your Connection! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string inthata {
            get {
                return ResourceManager.GetString("inthata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FFGapple Launcher aims to improve user experience and enhance service quality. IP addresses can be stored anonymously in memory. This is not done to track users or store personal data, but solely to limit excessive load or misuse. IP addresses are temporarily stored in memory, and user privacy is highly safeguarded. FFGapple Launcher doesn&apos;t share collected IP addresses with third parties or use them for commercial purposes. To proceed, confirm your understanding and click the &quot;Ok&quot; button to continue or the [dizenin kalan bölümü kesildi]&quot;; benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ipinf {
            get {
                return ResourceManager.GetString("ipinf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Accept benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string kabulet {
            get {
                return ResourceManager.GetString("kabulet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User agreement benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string kulsoz {
            get {
                return ResourceManager.GetString("kulsoz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Welcome to FFGapple Launcher. Before you begin, there are some things you need to review.
        ///
        ///FFGapple Minecraft Launcher
        ///Copyright (C) 2023 / ffgapple
        ///
        ///This program is free software: you can redistribute it and/or modify
        ///it under the terms of the GNU General Public License as published by
        ///the Free Software Foundation, either version 3 of the License, or
        ///(at your option) any later version.
        ///
        ///This program is distributed in the hope that it will be useful,
        ///but WITHOUT ANY WARRANTY; without even the imp [dizenin kalan bölümü kesildi]&quot;; benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string legal {
            get {
                return ResourceManager.GetString("legal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Let&apos;s get started benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string letsdone {
            get {
                return ResourceManager.GetString("letsdone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Optimizing... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string loadinf {
            get {
                return ResourceManager.GetString("loadinf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FFGapple Main System Is Damaged! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string mainbroke {
            get {
                return ResourceManager.GetString("mainbroke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I Have A Microsoft Account benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string mcacc {
            get {
                return ResourceManager.GetString("mcacc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Choose a Minecraft Edition! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string mcvererr {
            get {
                return ResourceManager.GetString("mcvererr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This optimization tool looks for the amount of memory in your system and allocates enough memory for the game. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string memred {
            get {
                return ResourceManager.GetString("memred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete Profile benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string minustool {
            get {
                return ResourceManager.GetString("minustool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Mod Folder ⤵ benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string modfolder {
            get {
                return ResourceManager.GetString("modfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Incorrect E-Mail or Password specified in the profile! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string mojhata {
            get {
                return ResourceManager.GetString("mojhata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Go forward benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string next {
            get {
                return ResourceManager.GetString("next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter a Nickname! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string nick {
            get {
                return ResourceManager.GetString("nick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Offline Login (Profiling System) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string offacc {
            get {
                return ResourceManager.GetString("offacc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   16GB RAM For Game (FFGapple Optimizing Tool) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string onaltigb {
            get {
                return ResourceManager.GetString("onaltigb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I Have A Original Account! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string orjhesap {
            get {
                return ResourceManager.GetString("orjhesap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   32GB RAM For Game (FFGapple Optimizing Tool) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string otuzikigb {
            get {
                return ResourceManager.GetString("otuzikigb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Restrict Minecraft multiplayer benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string pamm {
            get {
                return ResourceManager.GetString("pamm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Restrict profile management benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string papr {
            get {
                return ResourceManager.GetString("papr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parental lock activated 👨‍👩‍👧‍👦 benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string parenton {
            get {
                return ResourceManager.GetString("parenton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parental control settings benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string parentset {
            get {
                return ResourceManager.GetString("parentset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Restrict access to settings benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string paset {
            get {
                return ResourceManager.GetString("paset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create a new password benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string passnew {
            get {
                return ResourceManager.GetString("passnew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string passplace {
            get {
                return ResourceManager.GetString("passplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter your password benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string passw {
            get {
                return ResourceManager.GetString("passw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parental controls ensure your children stay safe online. Your child can use the FFGapple Launcher within the limits you set. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string pc {
            get {
                return ResourceManager.GetString("pc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ping Process Failed! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string pinghata {
            get {
                return ResourceManager.GetString("pinghata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mojang &amp; Microsoft E-Mail benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string place1 {
            get {
                return ResourceManager.GetString("place1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string place2 {
            get {
                return ResourceManager.GetString("place2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Play ▶  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string play {
            get {
                return ResourceManager.GetString("play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Preparing! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string prep {
            get {
                return ResourceManager.GetString("prep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Custom Directory: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string privdir {
            get {
                return ResourceManager.GetString("privdir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Profile directory benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string prodir {
            get {
                return ResourceManager.GetString("prodir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to Add Profile! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string proferr {
            get {
                return ResourceManager.GetString("proferr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Profile Name: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string profilenametext {
            get {
                return ResourceManager.GetString("profilenametext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter a Profile Name! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string profnamerr {
            get {
                return ResourceManager.GetString("profnamerr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Profile Overview benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string profov {
            get {
                return ResourceManager.GetString("profov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} GB RAM For Game benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ram {
            get {
                return ResourceManager.GetString("ram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ready For Launch! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ready {
            get {
                return ResourceManager.GetString("ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reject benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string reddet {
            get {
                return ResourceManager.GetString("reddet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Refresh benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string refreshtool {
            get {
                return ResourceManager.GetString("refreshtool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FFGapple - Resources Loading benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string resor {
            get {
                return ResourceManager.GetString("resor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   8GB RAM For Game (FFGapple Optimizing Tool) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string sekizgb {
            get {
                return ResourceManager.GetString("sekizgb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Skin benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string selectsk {
            get {
                return ResourceManager.GetString("selectsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You need to first select the profile you want to edit! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string seled {
            get {
                return ResourceManager.GetString("seled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Game Cannot Be Started, Select A Version For Start The Game! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string selver {
            get {
                return ResourceManager.GetString("selver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check Updates Automatically: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string set1 {
            get {
                return ResourceManager.GetString("set1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Other Versions: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string set2 {
            get {
                return ResourceManager.GetString("set2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Language: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string set3 {
            get {
                return ResourceManager.GetString("set3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string set4 {
            get {
                return ResourceManager.GetString("set4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit After The Starting To Game: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string setname {
            get {
                return ResourceManager.GetString("setname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string setto {
            get {
                return ResourceManager.GetString("setto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select a valid file! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string skinerr {
            get {
                return ResourceManager.GetString("skinerr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The &quot;Skin&quot; package has been created successfully, you can use the package you created by selecting the &quot;Custom Skin Pack&quot; package in the game to apply it. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string skinok {
            get {
                return ResourceManager.GetString("skinok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Snapshots benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string snapbtt {
            get {
                return ResourceManager.GetString("snapbtt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Started! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string started {
            get {
                return ResourceManager.GetString("started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FFGapple Cannot Start The Game, Please Check Your FireWall. If Your System OK, Contact From GitHub. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string startfail {
            get {
                return ResourceManager.GetString("startfail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to delete the profile named {0}? This action cannot be undone! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string suredel {
            get {
                return ResourceManager.GetString("suredel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Basic settings have been changed. Please restart to apply the changes. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string temelayar {
            get {
                return ResourceManager.GetString("temelayar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FFGapple is an open source Minecraft Launcher developed by a high school student since 2021. If you want to contribute to me, you can choose the donation amount you want from the buttons below and contribute to me! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string tip {
            get {
                return ResourceManager.GetString("tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Operating System Is Not Supporting By FFGapple! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string uop {
            get {
                return ResourceManager.GetString("uop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FFGapple - Updates Disabled benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string upbroke {
            get {
                return ResourceManager.GetString("upbroke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The new version cannot be installed. We will address this issue. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string uperr {
            get {
                return ResourceManager.GetString("uperr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A new update has been found, but it cannot be installed because automatic updates are turned off! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string upwont {
            get {
                return ResourceManager.GetString("upwont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Welcome to FFGapple, the open source, free, fast Minecraft Launcher!
        ///
        ///
        ///You can log in with Mojang by entering your Microsoft &amp; Mojang e-mail and password with the green field, if you don&apos;t have an account, you don&apos;t have to worry! From the red area, you can enter the game with the nickname you want by pressing the Offline login button! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string user1 {
            get {
                return ResourceManager.GetString("user1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This is the Main Menu for Profile System Logins,
        ///
        ///You can add as many profiles as you want from the Green Zone point.
        ///
        ///You can delete the profile you selected from the blue area dot.
        ///
        ///You can edit the profile you have chosen from the point with the purple area.
        ///
        ///You can refresh the profile list from the dot with the orange area.
        ///
        ///You can select a profile from the point with the red area.
        ///
        ///You can start playing the game right from the point with the yellow area! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string user2 {
            get {
                return ResourceManager.GetString("user2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   What is adding a profile?
        ///
        ///
        ///The FFGapple Profile system is a technology that allows you to quickly log into the game without wasting your time. With the settings you set, you can quickly open the game and enjoy!
        ///
        ///
        ///FFGapple will automatically detect the native language on your computer and translate all texts into your native language, no extra action! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string user3 {
            get {
                return ResourceManager.GetString("user3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   What is profile editing?
        ///
        ///
        ///You can change your profile settings as you wish. FFGapple will translate texts into your native language. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string user4 {
            get {
                return ResourceManager.GetString("user4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings menu
        ///
        ///You can access this menu by right click and settings.
        ///
        ///Here you can customize FFGapple according to you. You are free, as you wish :)! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string user5 {
            get {
                return ResourceManager.GetString("user5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Thanks for using FFGapple,
        ///
        ///There is so much more to discover, what are you waiting for. Shall we start the adventure :) ? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string user6 {
            get {
                return ResourceManager.GetString("user6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Let&apos;s go! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string userbut {
            get {
                return ResourceManager.GetString("userbut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User Manual benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string usermanual {
            get {
                return ResourceManager.GetString("usermanual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter a Username! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string usernameerr {
            get {
                return ResourceManager.GetString("usernameerr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Username: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string usernametext {
            get {
                return ResourceManager.GetString("usernametext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XBOX / Microsoft benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string userplace {
            get {
                return ResourceManager.GetString("userplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FFGapple Cannot Get The Version List! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string verno {
            get {
                return ResourceManager.GetString("verno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Version: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string versel {
            get {
                return ResourceManager.GetString("versel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Windows 7 are supported by FFGapple 3.9. Would you like to use this version? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string w87 {
            get {
                return ResourceManager.GetString("w87", resourceCulture);
            }
        }
        
        /// <summary>
        ///   On Windows 8.1, FFGapple may not work as expected. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string w8err {
            get {
                return ResourceManager.GetString("w8err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are some files required for FFGapple to work, without them FFGapple cannot work. Do you approve the download? File: WebView2 From Microsoft benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string webview {
            get {
                return ResourceManager.GetString("webview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Selected Profile:  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XML Files Damaged, Failed to Copy. The Program Goes To Repair Mode. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string xmlerr {
            get {
                return ResourceManager.GetString("xmlerr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Height: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string yuksektext {
            get {
                return ResourceManager.GetString("yuksektext", resourceCulture);
            }
        }
    }
}
